### ISSUE TITLE
May not be a JSON file

### ISSUE THREAD

**Issue by Andrei1911** [motiondeveloper/eKeys#2]
I think this is awesome, but it's not a json file.
It's an object, eKeys, that you create. It's javascript. 
I'm telling you this not as a critique but to let you know that you can use any of the javascript language benefits.

**Comment by timhaywood** [comment]
Thanks for the feedback Andrei!

My understanding based on [this article](https://helpx.adobe.com/au/after-effects/using/data-driven-animations.html) from Adobe was that `.jsx` files are still JSON, but the different extension bypasses the strict checking of the JSON parser to allow the embedding of functions (which are not part of the JSON spec).

So I think it's JSON file that has JavaScript _embedded_ rather than a JavaScript _file_ (which I don't believe AE will import) and still needs to adhere to the JSON spec (apart from the embedding of functions). Which is why it needs to be wrapped in `{}` and adhere to the key-value format.

I'll update the README to make this clearer, let me know if there's anything else I can improve!
